export const IS_LOADING = 'IS_LOADING';
export const RESTRAUNT_LIST_SUCCESS = 'RESTRAUNT_LIST_SUCCESS';
export const DISCOUNT_OFFERS_LIST_SUCCESS = 'DISCOUNT_OFFERS_LIST_SUCCESS';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const RESET_CART = 'RESET_CART';


